/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalapp.views;

import autonoma.hospitalapp.models.Hospital;
import autonoma.hospitalapp.models.Reporte;
import autonoma.hospitalapp.models.SistemaCentral;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * @author María Paz Puerta Acevedo <mariap.puertaa@autonoma.edu.co>
 * @since 20250414
 * @see autonoma.hospitalapp.views.GestionarReportes
 * @version 1.0.0
 */
public class GestionarReportes extends javax.swing.JDialog {
    private SistemaCentral sistema;

    /**
     * Creates new form GestionarReportes
     */
    public GestionarReportes(java.awt.Frame parent, boolean modal, SistemaCentral sistema) {
        super(parent, modal);
        initComponents();
        setSize(620, 700);
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.sistema = sistema;
         
        try{ 
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/HospitalApp/images/hospital.png")).getImage());
        
        }catch(NullPointerException e){
            System.out.println("Imagen no encontrada");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGenerarReporteEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarReportePacientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGenerarReporteFarmacia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atras4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 186, 238));

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Módulo Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarReporteEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarReporteEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarReporteEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteEmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReporteEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReporteEmpleadosMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospitalapp/images/GenerarReporteEmpleados.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Generar Reporte de Empleados");

        javax.swing.GroupLayout btnGenerarReporteEmpleadosLayout = new javax.swing.GroupLayout(btnGenerarReporteEmpleados);
        btnGenerarReporteEmpleados.setLayout(btnGenerarReporteEmpleadosLayout);
        btnGenerarReporteEmpleadosLayout.setHorizontalGroup(
            btnGenerarReporteEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteEmpleadosLayout.createSequentialGroup()
                .addGroup(btnGenerarReporteEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnGenerarReporteEmpleadosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(btnGenerarReporteEmpleadosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        btnGenerarReporteEmpleadosLayout.setVerticalGroup(
            btnGenerarReporteEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteEmpleadosLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        btnGenerarReportePacientes.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarReportePacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarReportePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReportePacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReportePacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReportePacientesMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Generar Reporte de Pacientes");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospitalapp/images/GenerarReportePaciente.png"))); // NOI18N

        javax.swing.GroupLayout btnGenerarReportePacientesLayout = new javax.swing.GroupLayout(btnGenerarReportePacientes);
        btnGenerarReportePacientes.setLayout(btnGenerarReportePacientesLayout);
        btnGenerarReportePacientesLayout.setHorizontalGroup(
            btnGenerarReportePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReportePacientesLayout.createSequentialGroup()
                .addGroup(btnGenerarReportePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnGenerarReportePacientesLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6))
                    .addGroup(btnGenerarReportePacientesLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGenerarReportePacientesLayout.setVerticalGroup(
            btnGenerarReportePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReportePacientesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnGenerarReporteFarmacia.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarReporteFarmacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerarReporteFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteFarmaciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReporteFarmaciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReporteFarmaciaMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospitalapp/images/GenerarReporteFarmacia.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Generar Reporte de Farmacia");

        javax.swing.GroupLayout btnGenerarReporteFarmaciaLayout = new javax.swing.GroupLayout(btnGenerarReporteFarmacia);
        btnGenerarReporteFarmacia.setLayout(btnGenerarReporteFarmaciaLayout);
        btnGenerarReporteFarmaciaLayout.setHorizontalGroup(
            btnGenerarReporteFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteFarmaciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnGenerarReporteFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGenerarReporteFarmaciaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGenerarReporteFarmaciaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17))))
        );
        btnGenerarReporteFarmaciaLayout.setVerticalGroup(
            btnGenerarReporteFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGenerarReporteFarmaciaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        Atras4.setBackground(new java.awt.Color(204, 0, 51));
        Atras4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Atras4.setForeground(new java.awt.Color(255, 255, 255));
        Atras4.setText("Atrás");
        Atras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenerarReporteEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarReportePacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarReporteFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(Atras4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnGenerarReporteEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnGenerarReportePacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnGenerarReporteFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Atras4)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteEmpleadosMouseClicked

        Reporte reporte = new Reporte(sistema.getHospital().getEmpleados(),
        sistema.getHospital().getPacientes(),
        sistema.getHospital().getFarmacia());

        GenerarReporteEmpleados ventanaGenerarReporteEmpleados = null;
        try {
            ventanaGenerarReporteEmpleados = new GenerarReporteEmpleados(this, true, sistema, reporte);
        } catch (IOException ex) {
            Logger.getLogger(GestionarReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaGenerarReporteEmpleados.setVisible(true);

    }//GEN-LAST:event_btnGenerarReporteEmpleadosMouseClicked

    private void btnGenerarReporteEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteEmpleadosMouseEntered
        this.mouseEntered(btnGenerarReporteEmpleados);
    }//GEN-LAST:event_btnGenerarReporteEmpleadosMouseEntered

    private void btnGenerarReporteEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteEmpleadosMouseExited
        this.mouseExited(btnGenerarReporteEmpleados);
    }//GEN-LAST:event_btnGenerarReporteEmpleadosMouseExited

    private void btnGenerarReportePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportePacientesMouseClicked
        Reporte reporte = new Reporte(sistema.getHospital().getEmpleados(),
        sistema.getHospital().getPacientes(),
        sistema.getHospital().getFarmacia());

        GenerarReportePacientes ventanaGenerarReportePacientes = null;
        try {
            ventanaGenerarReportePacientes = new GenerarReportePacientes(this, true, sistema, reporte);
        } catch (IOException ex) {
            Logger.getLogger(GestionarReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaGenerarReportePacientes.setVisible(true);
    }//GEN-LAST:event_btnGenerarReportePacientesMouseClicked

    private void btnGenerarReportePacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportePacientesMouseEntered
        this.mouseEntered(btnGenerarReportePacientes);
    }//GEN-LAST:event_btnGenerarReportePacientesMouseEntered

    private void btnGenerarReportePacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportePacientesMouseExited
        this.mouseExited(btnGenerarReportePacientes);
    }//GEN-LAST:event_btnGenerarReportePacientesMouseExited

    private void btnGenerarReporteFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteFarmaciaMouseClicked
        Reporte reporte = new Reporte(sistema.getHospital().getEmpleados(),
        sistema.getHospital().getPacientes(),
        sistema.getHospital().getFarmacia());

        GenerarReporteFarmacia ventanaGenerarReporteFarmacia = null;
        try {
            ventanaGenerarReporteFarmacia = new GenerarReporteFarmacia(this, true, sistema, reporte);
        } catch (IOException ex) {
            Logger.getLogger(GestionarReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaGenerarReporteFarmacia.setVisible(true);
    }//GEN-LAST:event_btnGenerarReporteFarmaciaMouseClicked

    private void btnGenerarReporteFarmaciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteFarmaciaMouseEntered
        this.mouseEntered(btnGenerarReporteFarmacia);
    }//GEN-LAST:event_btnGenerarReporteFarmaciaMouseEntered

    private void btnGenerarReporteFarmaciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteFarmaciaMouseExited
        this.mouseExited(btnGenerarReporteFarmacia);
    }//GEN-LAST:event_btnGenerarReporteFarmaciaMouseExited

    private void Atras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Atras4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras4;
    private javax.swing.JPanel btnGenerarReporteEmpleados;
    private javax.swing.JPanel btnGenerarReporteFarmacia;
    private javax.swing.JPanel btnGenerarReportePacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void mouseEntered(JPanel panel) {
        panel.setBackground(new Color(200,255,255));
    }

    private void mouseExited(JPanel panel) {
        panel.setBackground(new Color(200,255,255));
    }
}
