/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalapp.views;

import autonoma.hospitalapp.exceptions.PacienteNoEncontradoException;
import autonoma.hospitalapp.models.Hospital;
import autonoma.hospitalapp.models.Paciente;
import autonoma.hospitalapp.models.SistemaCentral;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Maria Paz Puerta
 */
public class MostrarPacientes extends javax.swing.JDialog {
    private ArrayList<Paciente> pacientes;
    private SistemaCentral sistema;
    private DefaultTableModel modeloTabla;
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form MostrarPacientes
     */
    public MostrarPacientes(java.awt.Frame parent, boolean modal, SistemaCentral sistema, VentanaPrincipal ventanaPrincipa) {
        super(parent, modal);
        initComponents();
        setSize(550, 700);
        setResizable(false);
        this.setLocationRelativeTo(null);
        
        try{ 
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/HospitalApp/images/Hospital.png")).getImage());
        
        }catch(NullPointerException e){
            System.out.println("Imagen no encontrada");
            
        }
        this.sistema = sistema;
        this.sistema.getHospital().getPacientes();
        PacienteBuscar.setText("Ingresa el nombre del paciente a buscar");
        PacienteBuscar.setForeground(Color.GRAY);
        
        this.sistema = sistema;
        this.pacientes = sistema.getHospital().getPacientes();
        this.ventanaPrincipal = ventanaPrincipal;
        this.tablaPacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        this.tablaPacientes.setRowSelectionAllowed(true);
        this.tablaPacientes.setColumnSelectionAllowed(false);
        modeloTabla = new DefaultTableModel(new Object[]{"Nombre","Documento","Edad", "Correo", "Teléfono", "Estado"}, 0);
        tablaPacientes.setModel(modeloTabla);
        this.llenarTabla();
        tablaPacientes.setSelectionBackground(new Color(198, 244, 214));
        tablaPacientes.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()));
        tablaPacientes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());
        tablaPacientes.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        PacienteBuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        btnActualizar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        PacienteBuscar.setText("Ingresa el nombre del paciente");
        PacienteBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacienteBuscarMouseClicked(evt);
            }
        });
        PacienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteBuscarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/hospitalapp/images/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PacienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PacienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Documento", "Edad", "Correo", "Télefono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPacientes);
        if (tablaPacientes.getColumnModel().getColumnCount() > 0) {
            tablaPacientes.getColumnModel().getColumn(0).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(1).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(2).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(3).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(4).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(5).setResizable(false);
        }

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar ");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(58, 58, 58)
                .addComponent(btnEliminar)
                .addGap(206, 206, 206))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaPacientes.getSelectedRow();
    
        if (filaSeleccionada == -1) {  
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un amigo de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaPacientes.getModel();
    
        String nombre = (String) modelo.getValueAt(filaSeleccionada, 0);    

        int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Seguro que deseas eliminar a " + nombre + "?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION
         );

        if (confirmacion == JOptionPane.YES_OPTION) {  
            try {
                if (sistema.eliminarPaciente(nombre)) {
                    JOptionPane.showMessageDialog(this, "Empleado eliminado exitosamente.");
                     
                    actualizarTablaPacientes(); 
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (PacienteNoEncontradoException e) {
                JOptionPane.showMessageDialog(this, "No se encontró el amigo en el directorio.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void PacienteBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacienteBuscarMouseClicked
        if (PacienteBuscar.getText().equals("Ingresa el nombre del paciente a buscar")) {
            PacienteBuscar.setText("");
            PacienteBuscar.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_PacienteBuscarMouseClicked

    private void PacienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteBuscarActionPerformed

    public void llenarTabla() {
        DefaultTableModel modelDefault = new DefaultTableModel(new String[]{"Nombre","Documento","Edad", "Correo", "Teléfono", "Estado"}, this.pacientes.size());
        this.tablaPacientes.setModel (modelDefault);
    
        TableModel dataModel = tablaPacientes.getModel();
        for (int i=0; i< this.pacientes.size(); i++){
            Paciente paciente = this.pacientes.get(i);
        
            dataModel.setValueAt(paciente.getNombre(), i, 0); 
            dataModel.setValueAt(paciente.getDocumento(), i, 1); 
            dataModel.setValueAt(paciente.getEdad(), i, 2);
            dataModel.setValueAt(paciente.getCorreo(), i, 3);
            dataModel.setValueAt(paciente.getTelefono(), i, 4);
            dataModel.setValueAt(paciente.getEstadoPaciente(), i, 5);
        }
    }
    
    private void actualizarTablaPacientes() {
        DefaultTableModel modelo = (DefaultTableModel) tablaPacientes.getModel();
        modelo.setRowCount(0);  

        for (Paciente emp : sistema.getHospital().getPacientes()) {
            Object[] fila = {
               
                emp.getNombre(),
                emp.getDocumento(),
                emp.getEdad()
            };
            modelo.addRow(fila);  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PacienteBuscar;
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
